### ISSUE TITLE
Flatpak version of GNOME Calendar 3.34 doesn't connect to calendars in gnome-online-accounts on a GNOME 3.32 system

### ISSUE THREAD

**Issue by garrett** [flathub/org.gnome.Calendar#10]
GNOME Calendar from 3.34 no longer shows calendars from gnome-online accounts on a GNOME 3.32 system.

I think it might be related to the version of evolution-data-server. However, it might be a Flatpak related packaging issue too. For example, the Flatpak of Evolution 3.34 works fine on a 3.32 system.

Errors look like this:
```
(gnome-calendar:2): GcalManager-WARNING **: 11:13:38.409: Failed to open/connect to calendar: Unable to connect to “vacation.ics”: The name is not activatable

(gnome-calendar:2): GcalManager-WARNING **: 11:13:38.409: Failed to open/connect to calendar: Unable to connect to “Weekly time off”: The name is not activatable
```

There's a related issue upstream @ https://gitlab.gnome.org/GNOME/gnome-calendar/issues/453

**Comment by bilelmoussaoui** [comment]
Not a calendar issue, it was due to evolution-server breaking the API.
