### ISSUE TITLE
Build with debug symbols

### ISSUE THREAD

**Issue by Eonfge** [flathub/org.gnome.Calendar#18]
I've recently reported an issue related to GNOME calendar:
https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues/562

One of the first questions I got, was reproducing the bug with debug symbols. Which is weird, because I also installed `org.gnome.Calendar.Debug` and I was running in --devel mode.

Could you add the Debug symbols to the Flatpak package so that future bugs can be easier  traced?

**Comment by TingPing** [comment]
At a glance it does, nothing disables them.

**Comment by Eonfge** [comment]
Something else that could cause the stacktrace missing debug info GNOME Calendar?

**Comment by bilelmoussaoui** [comment]
Do you have org.gnome.Sdk.Debug installed as well?

**Comment by Eonfge** [comment]
Closing this issue. So long ago that I can't properly recall all the details.
