### ISSUE TITLE
First day of week system setting is not preserved

### ISSUE THREAD

**Issue by garrett** [flathub/org.gnome.Calendar#31]
I have my system set up with "Ireland (English)" to get metrics, page size, and other European formats (instead of US ones), but still have it be close enough to English-US (with dots for decimals instead of commas). One of these settings is having Monday as the first day.

In GNOME Shell, Monday is the first day. If I install GNOME Calendar as a native package from Fedora, it's correct. If I install it from the Fedora flatpak, it's also correct.

...But the Flathub version of GNOME Calendar has the first day of the week as Sunday, which is different from the rest of my system.

(This is also an issue with the GNOME Nightly development flatpak version of GNOME Calendar.)

**Comment by GeorgesStavracas** [comment]
The Settings portal now exposes the appropriate values that let Calendar use the host system first weekday
