### ISSUE TITLE
Gnome 44.1 point release is out

### ISSUE THREAD

**Issue by Scotty-Trees** [flathub/org.gnome.Calendar#69]
Greetings,

Just wanted to inform the maintainers that Gnome 44.1 point release was just pushed out on Fedora 38 today. Many flatpaks in the Gnome stack are already updated to their 44/44.1 components, but Gnome Calendar flatpak (and Gnome Connections flatpak too) are still using older 44 versions. Just wanted to see if the maintainers could bump to the latest point release when time is permitted of course, thank you. Cheers.

**Comment by A6GibKm** [comment]
Done. It will be in the repo in no more than 4 hours.

**Comment by Scotty-Trees** [comment]
Thank you! Have a great Friday and hope you enjoy your weekend. Cheers!
